[project]
name = "ai-venture-studio-hw1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crewai>=0.28.8",
    "crewai[tools]>=0.28.8",
    "openai>=1.0.0",
    "click>=8.2.1"
]
